### ISSUE TITLE
Top Levels BVH support

### ISSUE THREAD

**Issue by elviras9t** [world8th/vRt#4]
Problematic to add support it. May cause problems in most ray tracing projects.

**Comment by lieff** [comment]
Vote for this feature. It's also simplifies BVH re-build/re-fit for dynamic objects, so we can only re-fit top-level BVH and do not touch static objects.

**Comment by elviras9t** [comment]
We are now busy preparatory work. First, I am trying to raise funds for the acquisition of the RTX 2070 to also add support, conduct initial tests and debugs, and only after that we are going to begin to redraw the architecture to support several levels of BVH. But submitting a pull request is always welcome.

**Comment by elviras9t** [comment]
You now can try, but we still unable high performances at now.

**Comment by lieff** [comment]
Wow, that was fast :) I will try it, probably this weekend.
